FROM node:8.17.0-alpine3.9

RUN mkdir -p /usr/src/app/server

WORKDIR /usr/src/app/server

COPY ./Server/package*.json ./

RUN npm install

COPY ./Server /usr/src/app/server/

EXPOSE 3003 3000

CMD [ "npm", "run", "dev" ]